spring.application.name=SpringOauth2




#for Google
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

#for Github
spring.security.oauth2.client.registration.github.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_CLIENT_SECRET

#for facebook
spring.security.oauth2.client.registration.facebook.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR_CLIENT_SECRET
