spring.application.name=SpringBootProject10Springsecurity
#spring.security.user.name=vaibhav
#spring.security.user.password=SpringSecurity


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot
spring.datasource.username=postgres
spring.datasource.password=Admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect